import React, { useRef, useState, useMemo, useEffect } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import "./Invoice.css";
import {formatPhone} from "../../utils/formatters.ts";

type Client = {
  companyName: string;
  address: string;
  phone: string;
  email: string;
  date: string;
};

type Item = {
  description: string;
  quantity?: number;
  feet?: number;
  totalCost?: number;
};

export const Invoice: React.FC = () => {

  const invoiceRef = useRef<HTMLDivElement>(null);
  const today = new Date().toISOString().split("T")[0];

  /* ---------------- STATE ---------------- */

  const [deposit, setDeposit] = useState(0);
  const [invoiceNumber, setInvoiceNumber] = useState<number | null>(null);
  const [docType, setDocType] = useState<"invoice" | "estimate">("estimate");

  const [client, setClient] = useState<Client>({
    companyName: "",
    address: "",
    date: "",
    email: "",
    phone: ""
  });

  const [items, setItems] = useState<Item[]>([
    { description: "", quantity: undefined, feet: undefined, totalCost: undefined }
  ]);
  const [showNotes, setShowNotes] = useState(false);
  const [notes, setNotes] = useState("");


  // -------Invoice Number Generator -----------

  useEffect(() => {
    const min = 1000;
    const max = 10000;
    const number = Math.floor(Math.random() * (max - min + 1)) + min;
    setInvoiceNumber(number);
  }, []);

  //-------------Today's Date Auto Fill -----------

  useEffect(() => {
    updateClient("date", today);
  }, [today]);

  /* ---------------- HELPERS ---------------- */

  const updateClient = (field: keyof Client, value: string) => {
    setClient(prev => ({ ...prev, [field]: value }));
  };

  const updateItem = (
    index: number,
    field: keyof Item,
    value: string | number | undefined
  ) => {
    setItems(prev =>
      prev.map((item, i) =>
        i === index ? { ...item, [field]: value } : item
      )
    );
  };

  const addItem = () => {
    setItems(prev => [
      ...prev,
      { description: "", quantity: undefined, feet: undefined, totalCost: undefined }
    ]);
  };
  // ------------Calculos para estimados y expiracion -------
  const estimateExpiration = useMemo(() => {
      if (!client.date) return "";

      const d = new Date(client.date);
      if (isNaN(d.getTime())) return "";

      d.setDate(d.getDate() + 30);
      return d.toISOString().split("T")[0];
    }, [client.date]); 

  /* ---------------- TOTALS ---------------- */

  const subtotal = useMemo(
    () => items.reduce((sum, i) => sum + (i.totalCost || 0), 0),
    [items]
  );

  const finalTotal = subtotal; // aquí luego puedes sumar taxes, extras, etc.
  const balanceDue = Math.max(finalTotal - deposit, 0);

  /* ---------------- PRINT / PDF ---------------- */

  const handlePrint = () => window.print();

  const handleDownloadPDF = async () => {
    if (!invoiceRef.current) return;

    const canvas = await html2canvas(invoiceRef.current, { scale: 2 });
    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF("p", "mm", "a4");
    const width = pdf.internal.pageSize.getWidth();
    const height = (canvas.height * width) / canvas.width;

    pdf.addImage(imgData, "PNG", 0, 0, width, height);
    pdf.save("Invoice.pdf");
  };

  /* ---------------- RENDER ---------------- */

  return (
    <>
      

      <div className="invoice-container" ref={invoiceRef}>
        {/* HEADER */}
        <div className="invoice-header">
          <div className="invoice-header-top">
            <img src="images/Logo/lauries-logo-para-fondo-blanco.png" alt="" />
            <div className="invoice-actions">
              <button className="invoice-actions-print-button" onClick={handlePrint}>Print</button>
              <button className="invoice-actions-download-pdf-button" onClick={handleDownloadPDF}>Download PDF</button>
            </div>
          </div>
          <hr />
        </div>
        <div className="info-autogenerated">

          {/* -----Select Estimate or Invoice----- */}
          
          <div className="invoice-type-select">
              <label><strong>DOCUMENT TYPE:</strong></label>
              <select
                value={docType}
                onChange={e => setDocType(e.target.value as "invoice" | "estimate")}
              >
                <option value="invoice">Invoice</option>
                <option value="estimate">Estimate</option>
              </select>
          </div>
          
          {/* Metadata: Type selector + dates */}
          <div className="invoice-meta">
                  {/* LEFT: Invoice / Estimate title */}
              <div className="invoice-number">
                {docType === "invoice" ? (
                  <h2><strong>INVOICE #: </strong>{invoiceNumber}</h2>
                ) : (
                  <h2><strong>ESTIMATE</strong></h2>
                )}
              </div>
  

              <div className="info-autogenerated-date">
                  <label><strong>Date: </strong></label>
                  <input type="date" value={client.date} readOnly />
              </div>

              {docType === "estimate" && estimateExpiration && (
                  <div className="estimate-expiration">
                    <strong>Expires:</strong> {estimateExpiration}
                  </div>
              )}
          </div>
        </div>

        <hr />
        {/* INFO */}
        <div className="invoice-info">
          <div className="invoice-lauries-info">
            <p><strong>FROM:</strong></p>
            <p>Lauries Welding Group</p>
            <p>Ray Lauries</p>
            <p>786-486-8465</p>
            <p>invoice@lauriesweldinggroup.com </p>
          </div>

          <div>
            <p><strong>TO COMPANY:</strong></p>
            <div className="invoice-company-info">
                <div>
                  <label htmlFor="companyName">
                     Name:
                  </label>
                  <input
                    id="companyName"
                    value={client.companyName}
                    onChange={e => updateClient("companyName", e.target.value)}
                  />
                </div>
                <div>
                    <label htmlFor="address">
                      Address:
                    </label>
                    <input
                      id="address"
                      value={client.address}
                      onChange={e => updateClient("address", e.target.value)}
                    />
                </div>
                <div>
                  <label htmlFor="phone">Phone:</label>
                  <input
                    id="phone"
                    value={formatPhone(client.phone)}
                    onChange={(e) =>
                      updateClient("phone", e.target.value.replace(/\D/g, ""))
                    }
                  />
                </div>
                <div>
                  <label htmlFor="email">
                    Email:
                  </label>
                  <input
                    id="email"
                    value={client.email}
                    onChange={e => updateClient("email", e.target.value)}
                  />
                </div>
            </div>
          </div>
        </div>

        {/* TABLE */}

        {/* add buttons and notes section */}
          <div className="add-buttons"> 
              <button 
                    className="add-row-button" 
                    onClick={addItem}
                >
                  + Add Item 
                </button>
                
                <button
                    className="add-notes-button"
                    onClick={() => setShowNotes(prev => !prev)}
                >
                  + Add Notes
              </button>
          </div>
        {/* end of buttons and notes section */}
        
        <table className="invoice-table">
          <thead>
            <tr>
              <th>Description</th>
              <th>Qty</th>
              <th>Feet</th>
              <th>Total</th>
            </tr>
          </thead>

          <tbody>
            {items.map((item, i) => (
              <tr key={i}>
                <td className="col-desc">
                  <input
                    value={item.description}
                    onChange={e => updateItem(i, "description", e.target.value)}
                  />
                </td>

                <td className="col-num">
                  <input
                    type="number"
                    value={item.quantity ?? ""}
                    onChange={e =>
                      updateItem(i, "quantity",
                        e.target.value === "" ? undefined : Number(e.target.value)
                      )
                    }
                  />
                </td>

                <td className="col-num">
                  <input
                    type="number"
                    value={item.feet ?? ""}
                    onChange={e =>
                      updateItem(i, "feet",
                        e.target.value === "" ? undefined : Number(e.target.value)
                      )
                    }
                  />
                </td>

                <td className="col-money">
                  <span>$</span>
                  <input
                    type="number"
                    value={item.totalCost ?? ""}
                      onChange={e =>
                        updateItem(i, "totalCost",
                          e.target.value === "" ? undefined : Number(e.target.value)
                        )
                    }
                  />
                </td>
              </tr>
              
            ))}
            {showNotes && (
              <div className="invoice-notes-container">
                <div className="invoice-notes-header">
                  NOTES
                </div>

                <textarea
                  className="invoice-notes-textarea"
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  placeholder="Enter additional project notes, clarifications, or terms..."
                />
              </div>
            )}

          </tbody>
          <div className="invoice-summary">
            <p><strong>Subtotal:</strong> ${subtotal.toFixed(2)}</p>
            <p><strong>Total:</strong> ${finalTotal.toFixed(2)}</p>
            <p><strong>Deposit Required:$
                <input
                  className="invoice-summary-input"
                  type="number"
                  min="0"
                  max={finalTotal}
                  value={deposit}
                  onChange={e => setDeposit(Number(e.target.value))}
                />
              </strong>
            </p>
            <p><strong>Balance Due:</strong> ${balanceDue.toFixed(2)}</p>
          </div> 
        </table>


        {/* TOTALS */}
        
      </div>
    </>
  );
};
