name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Cambia a la rama que prefieras

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Actualiza a v3 para usar Node.js 20

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Mantén v3, pero configurado para Node.js 20
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build --if-present

    # - name: Run tests
    #   run: npm test

    - name: Deploy using FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: "ftps://waws-prod-blu-357.ftp.azurewebsites.windows.net/site/wwwroot"
        username: "CalculatorAppViewUser"
        password: "Estadosunidos#01"
        server-dir: "/site/wwwroot"